### ISSUE TITLE
Problem running Article code

### ISSUE THREAD

**Issue by tadam98** [wingedrasengan927/Tensorflow-2-Object-Detection-API-Flask-Application#2]
Hi,

I followed: https://towardsdatascience.com/deploy-tensorflow-object-detection-api-on-kubernetes-with-python-flask-and-docker-7a9513dd19e4.

$ docker run -d -p 5000:5000 tf-od-api:latest
2fd63b49badb78ffdfa622ed87be031127243fe33b7647b7ac52d13e4e05b67a

But:
$ python client.py --address http://127.0.0.1:5000 --image_path images/test_image.jpg --output_dir outputs/
Traceback (most recent call last):
  File "client.py", line 47, in <module>
    response = post_image(args.image_path, url)
  File "client.py", line 29, in post_image
    img = open(img_path, 'rb').read()
FileNotFoundError: [Errno 2] No such file or directory: 'images/test_image.jpg'

So I loaded all into code.
Now it finds the files.

But I get an exception that connection is refused.
$fuser 5000/tcp
null. which means no one is listening.

I added a **debugpy** to **main.py** in the **Dockerfile**
`CMD ["python3", "-m", "debugpy", "--listen", "0.0.0.0:5678", "--wait-for-client", "main.py"]`
And when I single stepped through main, it called utilities which failed on line 17:
`from object_detection.utils import ops as utils_ops`
No module named 'object_detection'

And this is inside the docker.

any idea?
Best,
Mickey

**Comment by wingedrasengan927** [comment]
Hey Mickey,
sorry the image name should be 'girl_image.jpg', and not 'test_image.jpg' 
I will update this.
and can you try again.

and regarding the docker errors:
1. check if the container is running as your connection is being refused.
2. did you add the debugpy line after the path has been added to the environment variable or before that?

Thank you.

**Comment by tadam98** [comment]
This is my docker file:
============================
FROM python:3.7

# install build utilities
RUN apt-get update && \
    apt-get install -y --no-install-recommends apt-utils && \
    apt-get -y upgrade

# clone the repository
RUN git clone --depth 1 https://github.com/tensorflow/models.git

# Install object detection api dependencies
RUN apt-get install -y protobuf-compiler python-pil python-lxml python-tk && \
    pip install Cython && \
    pip install contextlib2 && \
    pip install jupyter && \
    pip install matplotlib && \
    pip install pycocotools && \
    pip install opencv-python && \
    pip install flask && \
    pip install tensorflow && \
    pip install Pillow && \
    pip install debugpy && \
    pip install requests

# Get protoc 3.0.0, rather than the old version already in the container
RUN curl -OL "https://github.com/google/protobuf/releases/download/v3.0.0/protoc-3.0.0-linux-x86_64.zip" && \
    unzip protoc-3.0.0-linux-x86_64.zip -d proto3 && \
    mv proto3/bin/* /usr/local/bin && \
    mv proto3/include/* /usr/local/include && \
    rm -rf proto3 protoc-3.0.0-linux-x86_64.zip

# Run protoc on the object detection repo
RUN cd models/research && \
    protoc object_detection/protos/*.proto --python_out=.

# Set the PYTHONPATH to finish installing the API
ENV PYTHONPATH=$PYTHONPATH:/models/research/object_detection
ENV PYTHONPATH=$PYTHONPATH:/models/research/slim
ENV PYTHONPATH=$PYTHONPATH:/models/research

# clone the flask application
RUN git clone https://github.com/wingedrasengan927/Tensorflow-2-Object-Detection-API-Flask-Application.git

# set this as the working directory
WORKDIR /Tensorflow-2-Object-Detection-API-Flask-Application

# download the pretrained model
# change here to download your pretrained model
RUN mkdir models && \
    cd models/ && \
    curl -O "http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_fpn_shared_box_predictor_640x640_coco14_sync_2018_07_03.tar.gz" && \
    tar xzf ssd_mobilenet_v1_fpn_shared_box_predictor_640x640_coco14_sync_2018_07_03.tar.gz && \
    rm ssd_mobilenet_v1_fpn_shared_box_predictor_640x640_coco14_sync_2018_07_03.tar.gz

#CMD ["python", "main.py"]
CMD ["python3", "-m", "debugpy", "--listen", "0.0.0.0:5678", "--wait-for-client", "main.py"]

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by tadam98** [comment]
See attached build log.
And the image of the run-time error. As if the Tensorflow object detect is not properly installed.
[cid:image003.png@01D6ED0C.D86DBFF0]

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by tadam98** [comment]
Attached please find the client.run.log after I corrected the image name to girl_image.jpg
$ python client.py --address http://127.0.0.1:5000 --image_path images/girl_image.jpg --output_dir outputs/

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by wingedrasengan927** [comment]
Hey Mickey,
1. looks like this is an issue with debugpy, and it is not able to listen to the docker container. can you remove debugpy and try again
2. I couldn't find the log file you mentioned.

**Comment by tadam98** [comment]
After the build, I used:
```
$ fuser 5000/tcp # make sure port 5000 is free
$ docker run -d -p 5000:5000 tf-od-api:latest
23dd54549e0cdf6ee4ce63ca59e6c78b3591baf29b050da71e016403a905476a
$ docker logs 23dd54549e0c
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    import cv2
  File "/usr/local/lib/python3.7/site-packages/cv2/__init__.py", line 5, in <module>
    from .cv2 import *
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
[tf-od-api.build-2.log](https://github.com/wingedrasengan927/Tensorflow-2-Object-Detection-API-Flask-Application/files/5826621/tf-od-api.build-2.log)



```
[client.run2.log](https://github.com/wingedrasengan927/Tensorflow-2-Object-Detection-API-Flask-Application/files/5826625/client.run2.log)
[tf-od-api.build-2.log](https://github.com/wingedrasengan927/Tensorflow-2-Object-Detection-API-Flask-Application/files/5826626/tf-od-api.build-2.log)

**Comment by wingedrasengan927** [comment]
Hey Mickey,
Thanks for the log file.
I updated the Dockerfile with a temporary fix and tested it successfully.
It should work now.

Sorry for the inconvenience.
Closing this issue.

Thanks.

**Comment by tadam98** [comment]
by the way:
$ docker run -d -p 5000:5000 **-p 5678:5678** tf-od-api:latest

Ensures connection to the debugger.

Also, at least in my case --zone and --machine-type had to be added to the google cloud creation.

**Comment by wingedrasengan927** [comment]
Great thanks, will check it out
